---
# Before anything else, make sure the system is up to date.
# TODO: On secure boot systems this will break kernel updates.
# - name: Upgrade System
#   hosts: all
#   become: yes
#   tasks:
#     - name: Pacman -Syu
#       pacman:
#         update_cache: yes
#         upgrade: yes


- name: 'Role - Hypervisor'
  hosts: hypervisor
  become: true
  roles:
    - hypervisor

# Run tasks specific to this host if they exist.
- name: Host-specific tasks
  hosts: all
  tasks:
    - name: Load task list
      include_tasks: '{{ item }}'
      with_first_found:
        - files:
          - 'roles/{{ inventory_hostname }}.yml'
          skip: true

