---
# Before anything else, make sure the system is up to date.
# TODO: On secure boot systems this will break kernel updates.
# - name: Upgrade System
#   hosts: all
#   become: yes
#   tasks:
#     - name: Pacman -Syu
#       pacman:
#         update_cache: yes
#         upgrade: yes

- name: 'Enable ansible-pull periodically'
  become: true
  hosts: pull_config
  vars:
    ansible_pull_dir: '/var/tmp/ansible'
    ansible_pull_url: 'https://github.com/alxbl/config'
    ansible_pull_hosts: 'hosts'
    ansible_pull_playbook: 'playbook.yml'
  tasks:
    - name: Configure ansible service
      template:
        src: files/common/ansibled.service.j2
        dest: /usr/lib/systemd/system/ansibled.service
        owner: root
        groups: root
        mode: 0644
    - name: Configure ansible timer
      block:
        - copy:
            src: files/common/ansibled.timer
            dest: /usr/lib/systemd/system/ansibled.timer
            owner: root
            groups: root
            mode: 0644
        - service:
            name: ansibled.timer
            enabled: true
            state: started

- hosts: hypervisor
  become: true
  roles:
    - hypervisor

# Run tasks specific to this host if they exist.
- name: Host-specific tasks
  hosts: all
  tasks:
    - name: Load task list
      include_tasks: '{{ item }}'
      with_first_found:
        - files:
          - 'roles/{{ inventory_hostname }}.yml'
          skip: true

