---
    - name: Install virtualization packages
      pacman:
        name: qemu,ovmf,dnsmasq,libvirt

    # dnsmasq
    - name: Configure dnsmasq
      block:
        - copy:
            src:  files/dnsmasq
            dest: /var/lib/dnsmasq
          name: Configure dnsmasq

        - copy:
            src: files/dnsmasq@.service
            dest: /usr/lib/systemd/system/dnsmasq@.service
          name: Enable dnsmasq
          notify:
            - restart dnsmasq

        - copy:
            src: files/qemu0/
            dest: /usr/lib/systemd/network
          name: Configure network bridge
          notify:
            - restart networkd

        - service:
            name: dnsmasq@qemu0
            enabled: true
            state: started
          name: Enable dnsmasq

    - name: Configure libvirtd
      block:
        - service:
            name: libvirtd
            enabled: true
            state: started
          name: Enable libvirtd

        - service:
            name: virtlogd
            enabled: true
            state: started
          name: Enable virtlogd

