---
- name: Install graphical user interface
  pacman:
    name:
      - fcitx
      - fcitx-mozc
      - fcitx-configtool
      - awesome
      - unclutter
      - flameshot
      - rdesktop
      - ttf-droid
      - noto-fonts
      - noto-fonts-cjk
      - noto-fonts-emoji
      - gimp
      - inkscape
      - networkmanager

